// GkoShellExt.idl : IDL source for GkoShellExt
//

// This file will be processed by the MIDL tool to
// produce the type library (GkoShellExt.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(a817e7a2-43fa-11d0-9e44-00aa00b6770a),
	dual,
	helpstring("IComponentRegistrar Interface"),
	pointer_default(unique)
]
interface IComponentRegistrar : IDispatch
{
	[id(1)]	HRESULT Attach([in] BSTR bstrPath);
	[id(2)]	HRESULT RegisterAll();
	[id(3)]	HRESULT UnregisterAll();
	[id(4)]	HRESULT GetComponents([out] SAFEARRAY(BSTR)* pbstrCLSIDs, [out] SAFEARRAY(BSTR)* pbstrDescriptions);
	[id(5)]	HRESULT RegisterComponent([in] BSTR bstrCLSID);
	[id(6)] HRESULT UnregisterComponent([in] BSTR bstrCLSID);
};

[
	object,
	uuid(DE85BF1D-8185-4C31-94FC-C19EE6E4C7F9),
	dual,
	nonextensible,
	helpstring("IGingkoContextMenuExt Interface"),
	pointer_default(unique)
]
interface IGingkoContextMenuExt : IDispatch{
};
[
	uuid(1A0BE39A-A0A0-4D53-B64E-DCC4CDFFC244),
	version(1.0),
	helpstring("GkoShellExt 1.0 Type Library"),
	custom(a817e7a1-43fa-11d0-9e44-00aa00b6770a,"{D1046D0B-8B45-461D-A3C8-253F93958D3F}")
]
library GkoShellExtLib
{
	importlib("stdole2.tlb");

	[
		uuid(D1046D0B-8B45-461D-A3C8-253F93958D3F),
		helpstring("ComponentRegistrar Class")
	]
	coclass CompReg
	{
		[default] interface IComponentRegistrar;
	};
	[
		uuid(7DFB6A6B-8CB7-4B1B-9CA9-6C9F11E923C9),
		helpstring("CGingkoContextMenuExt Class")
	]
	coclass CGingkoContextMenuExt
	{
		[default] interface IGingkoContextMenuExt;
	};
};
