//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GingkoShell.rc
//
#define IDC_MYICON                      2
#define IDD_GINGKOSHELL_DIALOG          102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_GINGKOSHELL                 107
#define IDI_SMALL                       108
#define IDC_GINGKOSHELL                 109
#define IDC_HYPERLINK                   109
#define IDR_MAINFRAME                   128
#define IDD_MAINDLG                     129
#define IDB_LISTITEMS                   130
#define IDC_HYPERLINK1                  133
#define IDC_DIVIDER                     133
#define IDD_DETAIL                      135
#define IDD_SECURITY                    136
#define IDD_SHARE                       137
#define IDD_OPTIONS_DIALOG              138
#define IDD_PASSWORD_DIALOG             139
#define IDD_LOGIN_DIALOG                140
#define IDD_REQ_PERM_DIALOG             141
#define IDD_ASSOCIATE_DIALOG            142
#define IDR_POPUP                       143
#define IDB_DISP_NO                     146
#define IDB_BITMAP2                     147
#define IDB_DISP_PASS                   147
#define IDC_EDIT_FILENAME               1000
#define IDC_BROWSER                     1001
#define IDC_CHK_ENCRYPT_ONLY            1002
#define IDC_TAB_PANEL                   1003
#define IDC_TOP_BAR                     1004
#define IDC_FILE_INFO_GROUP             1005
#define IDC_FILE_NAME                   1006
#define IDC_USER_LIST                   1007
#define IDC_BTN_DELETE                  1007
#define IDC_EDIT_EMAIL                  1008
#define IDC_BTN_CHECK_ADD               1009
#define IDC_GROUP_DETAIL                1010
#define IDC_TITLE                       1011
#define IDC_BTN_REMOVE_USER             1011
#define IDC_EDIT_TITLE                  1012
#define IDC_BTN_SHARE_ROUTE             1012
#define IDC_AUTHOR                      1013
#define IDC_CMB_SHARED_OPTIONS          1013
#define IDC_EDIT_AUTHOR                 1014
#define IDC_USER_EMAIL                  1014
#define IDC_CMB_SECURITY_OPTIONS        1014
#define IDC_KEYWORDS                    1015
#define IDC_CMB_LIMITATIONS_1           1015
#define IDC_CMB_LIMITATIONS             1015
#define IDC_EDIT_KEYWORDS               1016
#define IDC_SECURITY_GROUP              1016
#define IDC_DESCRIPTION                 1017
#define IDC_SHARED_OPTIONS              1017
#define IDC_EDIT_DESCRIPTION            1018
#define IDC_SECURITY_OPTIONS            1018
#define IDC_LIMITATIONS                 1019
#define IDC_SHARE_GROUP                 1020
#define IDC_RD_WW                       1025
#define IDC_RD_ORG                      1026
#define IDC_RADIO3                      1027
#define IDC_RD_UNIT                     1027
#define IDC_NO_PROXY                    1027
#define IDC_GROUP_LIMITS                1028
#define IDC_BUTTON1                     1029
#define IDC_BTN_OPTIONS                 1029
#define IDC_BTN_REQUEST                 1029
#define IDC_PRINT                       1029
#define IDC_ICON_ABOUT                  1030
#define IDC_SAVEAS                      1030
#define IDC_ABOUT_VERSION               1031
#define IDC_EDIT_USERID                 1032
#define IDC_EDIT_PASSWORD               1033
#define IDC_LBL_USERID                  1034
#define IDC_LBL_PASSWORD                1035
#define IDC_EDIT_PASSWORD_RET           1037
#define IDC_LBL_PASSWORDRET             1038
#define IDC_NEW_REGISTER                1039
#define IDC_LINK_GETPASSWORD            1040
#define IDC_PROXY_OPTIONS               1042
#define IDC_MISCELLANCEOUS              1043
#define IDC_MASTER_SERVER               1044
#define IDC_EDIT_UNIT_SERVER            1045
#define IDC_EDIT_PROXYSERVER            1046
#define IDC_EDIT_PROXYPORT              1047
#define IDC_EDIT_PROXY_USERNAME         1048
#define IDC_EDIT_PROXY_PASSWORD         1049
#define IDC_SAME_AS_IE                  1050
#define IDC_RD_CUSTOM                   1051
#define IDC_EDIT_CALL_TIMEOUT           1052
#define IDC_LBL_TIMEOUT                 1054
#define IDC_LBL_MASTER_SERVER           1056
#define IDC_LBL_UNITSERVER              1057
#define IDC_LBL_PROXYSERVER             1058
#define IDC_LBL_PROXYPORT               1059
#define IDC_LBL_PROXY_USERNAME          1060
#define IDC_LBL_PROXY_PASSWORD          1061
#define IDC_CBO_LANGUAGE                1062
#define IDC_LANGUAGE_INTERFACE          1063
#define IDC_SERVER_LIST_GROUP           1064
#define IDC_PRG_FILEPROCESS             1064
#define IDC_RQP_TOP_BAR                 1067
#define IDC_CHK_HOLDER                  1068
#define IDC_CHK_OWNER                   1069
#define IDC_CHK_READABLE                1070
#define IDC_CHK_WRITABLE                1071
#define IDC_CHK_PRINTABLE               1072
#define IDC_CHECK6                      1073
#define IDC_CHK_DELETABLE               1073
#define IDC_EDIT_MESSAGE                1074
#define IDC_LBL_MESSAGE                 1075
#define IDC_PERMS_GROUP                 1076
#define IDC_PERMS_REQ_GROUP             1076
#define IDC_LBL_REQPERMS                1077
#define IDC_MAIN_CONTAINER              1080
#define ID_POPUP_OPTIONS                32771
#define ID_POPUP_LOGIN                  32772
#define ID_POPUP_LOGOUT                 32773
#define ID_POPUP_EXIT                   32774
#define ID_POPUP_GINGKOSHARING          32775
#define ID_POPUP_GINGKOMAP              32776
#define ID_POPUP_DECRYPTFILE            32777
#define IDC_COPYRIGHTS                  -1
#define IDC_COPY_RIGHTS                 -1
#define IDC_COPYCOPY                    -1
#define IDC_PASSWORD_TOPBAR             -1
#define IDC_LOGIN_TOPBAR                -1
#define IDC_SERVER_LIST                 -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1077
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
