/* soapGingkoLoginSoapServiceBeanServiceSoapBindingProxy.h
   Generated by gSOAP 2.7.13 from GingkoWebService.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapGingkoLoginSoapServiceBeanServiceSoapBindingProxy_H
#define soapGingkoLoginSoapServiceBeanServiceSoapBindingProxy_H
#include "soapH.h"
class GingkoLoginSoapServiceBeanServiceSoapBinding
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'GingkoLoginSoapServiceBeanServiceSoapBinding' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	GingkoLoginSoapServiceBeanServiceSoapBinding()
	{ soap = soap_new(); endpoint = "http://localhost:8080/gingko/gkws/GingkoDigitalService http://localhost:8080/gingko/gkws/GingkoLoginService http://localhost:8080/gingko/gkws/GingkoUnitService http://localhost:8080/gingko/gkws/GingkoUserService"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
	{"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "http://soap.gingkos.s7turn.com/", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	/// Destructor frees deserialized data and soap engine context
	virtual ~GingkoLoginSoapServiceBeanServiceSoapBinding() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'registerUser' of service 'GingkoLoginSoapServiceBeanServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__registerUser(ns1__registerUser *ns1__registerUser_, ns1__registerUserResponse *ns1__registerUserResponse_) { return soap ? soap_call___ns1__registerUser(soap, endpoint, NULL, ns1__registerUser_, ns1__registerUserResponse_) : SOAP_EOM; };
	/// Invoke 'userLogin' of service 'GingkoLoginSoapServiceBeanServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__userLogin(ns1__userLogin *ns1__userLogin_, ns1__userLoginResponse *ns1__userLoginResponse_) { return soap ? soap_call___ns1__userLogin(soap, endpoint, NULL, ns1__userLogin_, ns1__userLoginResponse_) : SOAP_EOM; };
	/// Invoke 'gingkoVersion' of service 'GingkoLoginSoapServiceBeanServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__gingkoVersion(ns1__gingkoVersion *ns1__gingkoVersion_, ns1__gingkoVersionResponse *ns1__gingkoVersionResponse_) { return soap ? soap_call___ns1__gingkoVersion(soap, endpoint, NULL, ns1__gingkoVersion_, ns1__gingkoVersionResponse_) : SOAP_EOM; };
	/// Invoke 'newGingkoId' of service 'GingkoLoginSoapServiceBeanServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__newGingkoId(ns1__newGingkoId *ns1__newGingkoId_, ns1__newGingkoIdResponse *ns1__newGingkoIdResponse_) { return soap ? soap_call___ns1__newGingkoId(soap, endpoint, NULL, ns1__newGingkoId_, ns1__newGingkoIdResponse_) : SOAP_EOM; };
	/// Invoke 'checkToken' of service 'GingkoLoginSoapServiceBeanServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__checkToken(ns1__checkToken *ns1__checkToken_, ns1__checkTokenResponse *ns1__checkTokenResponse_) { return soap ? soap_call___ns1__checkToken(soap, endpoint, NULL, ns1__checkToken_, ns1__checkTokenResponse_) : SOAP_EOM; };
	/// Invoke 'registerThisUnit' of service 'GingkoLoginSoapServiceBeanServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__registerThisUnit(ns1__registerThisUnit *ns1__registerThisUnit_, ns1__registerThisUnitResponse *ns1__registerThisUnitResponse_) { return soap ? soap_call___ns1__registerThisUnit(soap, endpoint, NULL, ns1__registerThisUnit_, ns1__registerThisUnitResponse_) : SOAP_EOM; };
	/// Invoke 'findGingkoUnitInfo' of service 'GingkoLoginSoapServiceBeanServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__findGingkoUnitInfo(ns1__findGingkoUnitInfo *ns1__findGingkoUnitInfo_, ns1__findGingkoUnitInfoResponse *ns1__findGingkoUnitInfoResponse_) { return soap ? soap_call___ns1__findGingkoUnitInfo(soap, endpoint, NULL, ns1__findGingkoUnitInfo_, ns1__findGingkoUnitInfoResponse_) : SOAP_EOM; };
	/// Invoke 'bindingGingkoUser' of service 'GingkoLoginSoapServiceBeanServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__bindingGingkoUser(ns1__bindingGingkoUser *ns1__bindingGingkoUser_, ns1__bindingGingkoUserResponse *ns1__bindingGingkoUserResponse_) { return soap ? soap_call___ns1__bindingGingkoUser(soap, endpoint, NULL, ns1__bindingGingkoUser_, ns1__bindingGingkoUserResponse_) : SOAP_EOM; };
	/// Invoke 'findUserByLoginId' of service 'GingkoLoginSoapServiceBeanServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__findUserByLoginId(ns1__findUserByLoginId *ns1__findUserByLoginId_, ns1__findUserByLoginIdResponse *ns1__findUserByLoginIdResponse_) { return soap ? soap_call___ns1__findUserByLoginId(soap, endpoint, NULL, ns1__findUserByLoginId_, ns1__findUserByLoginIdResponse_) : SOAP_EOM; };
	/// Invoke 'searchUsers' of service 'GingkoLoginSoapServiceBeanServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__searchUsers(ns1__searchUsers *ns1__searchUsers_, ns1__searchUsersResponse *ns1__searchUsersResponse_) { return soap ? soap_call___ns1__searchUsers(soap, endpoint, NULL, ns1__searchUsers_, ns1__searchUsersResponse_) : SOAP_EOM; };
	/// Invoke 'findUserByGingkoId' of service 'GingkoLoginSoapServiceBeanServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__findUserByGingkoId(ns1__findUserByGingkoId *ns1__findUserByGingkoId_, ns1__findUserByGingkoIdResponse *ns1__findUserByGingkoIdResponse_) { return soap ? soap_call___ns1__findUserByGingkoId(soap, endpoint, NULL, ns1__findUserByGingkoId_, ns1__findUserByGingkoIdResponse_) : SOAP_EOM; };
	/// Invoke 'changePassword' of service 'GingkoLoginSoapServiceBeanServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__changePassword(ns1__changePassword *ns1__changePassword_, ns1__changePasswordResponse *ns1__changePasswordResponse_) { return soap ? soap_call___ns1__changePassword(soap, endpoint, NULL, ns1__changePassword_, ns1__changePasswordResponse_) : SOAP_EOM; };
	/// Invoke 'requestPermission' of service 'GingkoLoginSoapServiceBeanServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__requestPermission(ns1__requestPermission *ns1__requestPermission_, ns1__requestPermissionResponse *ns1__requestPermissionResponse_) { return soap ? soap_call___ns1__requestPermission(soap, endpoint, NULL, ns1__requestPermission_, ns1__requestPermissionResponse_) : SOAP_EOM; };
	/// Invoke 'deleteDigitalInfo' of service 'GingkoLoginSoapServiceBeanServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__deleteDigitalInfo(ns1__deleteDigitalInfo *ns1__deleteDigitalInfo_, ns1__deleteDigitalInfoResponse *ns1__deleteDigitalInfoResponse_) { return soap ? soap_call___ns1__deleteDigitalInfo(soap, endpoint, NULL, ns1__deleteDigitalInfo_, ns1__deleteDigitalInfoResponse_) : SOAP_EOM; };
	/// Invoke 'findDigitalInfo' of service 'GingkoLoginSoapServiceBeanServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__findDigitalInfo(ns1__findDigitalInfo *ns1__findDigitalInfo_, ns1__findDigitalInfoResponse *ns1__findDigitalInfoResponse_) { return soap ? soap_call___ns1__findDigitalInfo(soap, endpoint, NULL, ns1__findDigitalInfo_, ns1__findDigitalInfoResponse_) : SOAP_EOM; };
	/// Invoke 'findAssignedPermission' of service 'GingkoLoginSoapServiceBeanServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__findAssignedPermission(ns1__findAssignedPermission *ns1__findAssignedPermission_, ns1__findAssignedPermissionResponse *ns1__findAssignedPermissionResponse_) { return soap ? soap_call___ns1__findAssignedPermission(soap, endpoint, NULL, ns1__findAssignedPermission_, ns1__findAssignedPermissionResponse_) : SOAP_EOM; };
	/// Invoke 'assignPermission' of service 'GingkoLoginSoapServiceBeanServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__assignPermission(ns1__assignPermission *ns1__assignPermission_, ns1__assignPermissionResponse *ns1__assignPermissionResponse_) { return soap ? soap_call___ns1__assignPermission(soap, endpoint, NULL, ns1__assignPermission_, ns1__assignPermissionResponse_) : SOAP_EOM; };
	/// Invoke 'findDigitalPermission' of service 'GingkoLoginSoapServiceBeanServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__findDigitalPermission(ns1__findDigitalPermission *ns1__findDigitalPermission_, ns1__findDigitalPermissionResponse *ns1__findDigitalPermissionResponse_) { return soap ? soap_call___ns1__findDigitalPermission(soap, endpoint, NULL, ns1__findDigitalPermission_, ns1__findDigitalPermissionResponse_) : SOAP_EOM; };
	/// Invoke 'updateDigitalInfo' of service 'GingkoLoginSoapServiceBeanServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__updateDigitalInfo(ns1__updateDigitalInfo *ns1__updateDigitalInfo_, ns1__updateDigitalInfoResponse *ns1__updateDigitalInfoResponse_) { return soap ? soap_call___ns1__updateDigitalInfo(soap, endpoint, NULL, ns1__updateDigitalInfo_, ns1__updateDigitalInfoResponse_) : SOAP_EOM; };
	/// Invoke 'createDigitalInfo' of service 'GingkoLoginSoapServiceBeanServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__createDigitalInfo(ns1__createDigitalInfo *ns1__createDigitalInfo_, ns1__createDigitalInfoResponse *ns1__createDigitalInfoResponse_) { return soap ? soap_call___ns1__createDigitalInfo(soap, endpoint, NULL, ns1__createDigitalInfo_, ns1__createDigitalInfoResponse_) : SOAP_EOM; };
};
#endif
