/* soapClient.cpp
   Generated by gSOAP 2.7.13 from GingkoWebService.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.7.13 2009-11-12 07:22:20 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__registerUser(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__registerUser *ns1__registerUser_, ns1__registerUserResponse *ns1__registerUserResponse_)
{	struct __ns1__registerUser soap_tmp___ns1__registerUser;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080/gingko/gkws/GingkoDigitalService http://localhost:8080/gingko/gkws/GingkoLoginService http://localhost:8080/gingko/gkws/GingkoUnitService http://localhost:8080/gingko/gkws/GingkoUserService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__registerUser.ns1__registerUser_ = ns1__registerUser_;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__registerUser(soap, &soap_tmp___ns1__registerUser);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__registerUser(soap, &soap_tmp___ns1__registerUser, "-ns1:registerUser", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__registerUser(soap, &soap_tmp___ns1__registerUser, "-ns1:registerUser", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__registerUserResponse_)
		return soap_closesock(soap);
	ns1__registerUserResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__registerUserResponse_->soap_get(soap, "ns1:registerUserResponse", "ns1:registerUserResponse");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__userLogin(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__userLogin *ns1__userLogin_, ns1__userLoginResponse *ns1__userLoginResponse_)
{	struct __ns1__userLogin soap_tmp___ns1__userLogin;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080/gingko/gkws/GingkoDigitalService http://localhost:8080/gingko/gkws/GingkoLoginService http://localhost:8080/gingko/gkws/GingkoUnitService http://localhost:8080/gingko/gkws/GingkoUserService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__userLogin.ns1__userLogin_ = ns1__userLogin_;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__userLogin(soap, &soap_tmp___ns1__userLogin);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__userLogin(soap, &soap_tmp___ns1__userLogin, "-ns1:userLogin", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__userLogin(soap, &soap_tmp___ns1__userLogin, "-ns1:userLogin", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__userLoginResponse_)
		return soap_closesock(soap);
	ns1__userLoginResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__userLoginResponse_->soap_get(soap, "ns1:userLoginResponse", "ns1:userLoginResponse");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__gingkoVersion(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__gingkoVersion *ns1__gingkoVersion_, ns1__gingkoVersionResponse *ns1__gingkoVersionResponse_)
{	struct __ns1__gingkoVersion soap_tmp___ns1__gingkoVersion;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080/gingko/gkws/GingkoDigitalService http://localhost:8080/gingko/gkws/GingkoLoginService http://localhost:8080/gingko/gkws/GingkoUnitService http://localhost:8080/gingko/gkws/GingkoUserService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__gingkoVersion.ns1__gingkoVersion_ = ns1__gingkoVersion_;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__gingkoVersion(soap, &soap_tmp___ns1__gingkoVersion);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__gingkoVersion(soap, &soap_tmp___ns1__gingkoVersion, "-ns1:gingkoVersion", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__gingkoVersion(soap, &soap_tmp___ns1__gingkoVersion, "-ns1:gingkoVersion", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__gingkoVersionResponse_)
		return soap_closesock(soap);
	ns1__gingkoVersionResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__gingkoVersionResponse_->soap_get(soap, "ns1:gingkoVersionResponse", "ns1:gingkoVersionResponse");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__newGingkoId(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__newGingkoId *ns1__newGingkoId_, ns1__newGingkoIdResponse *ns1__newGingkoIdResponse_)
{	struct __ns1__newGingkoId soap_tmp___ns1__newGingkoId;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080/gingko/gkws/GingkoDigitalService http://localhost:8080/gingko/gkws/GingkoLoginService http://localhost:8080/gingko/gkws/GingkoUnitService http://localhost:8080/gingko/gkws/GingkoUserService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__newGingkoId.ns1__newGingkoId_ = ns1__newGingkoId_;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__newGingkoId(soap, &soap_tmp___ns1__newGingkoId);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__newGingkoId(soap, &soap_tmp___ns1__newGingkoId, "-ns1:newGingkoId", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__newGingkoId(soap, &soap_tmp___ns1__newGingkoId, "-ns1:newGingkoId", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__newGingkoIdResponse_)
		return soap_closesock(soap);
	ns1__newGingkoIdResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__newGingkoIdResponse_->soap_get(soap, "ns1:newGingkoIdResponse", "ns1:newGingkoIdResponse");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__checkToken(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__checkToken *ns1__checkToken_, ns1__checkTokenResponse *ns1__checkTokenResponse_)
{	struct __ns1__checkToken soap_tmp___ns1__checkToken;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080/gingko/gkws/GingkoDigitalService http://localhost:8080/gingko/gkws/GingkoLoginService http://localhost:8080/gingko/gkws/GingkoUnitService http://localhost:8080/gingko/gkws/GingkoUserService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__checkToken.ns1__checkToken_ = ns1__checkToken_;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__checkToken(soap, &soap_tmp___ns1__checkToken);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__checkToken(soap, &soap_tmp___ns1__checkToken, "-ns1:checkToken", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__checkToken(soap, &soap_tmp___ns1__checkToken, "-ns1:checkToken", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__checkTokenResponse_)
		return soap_closesock(soap);
	ns1__checkTokenResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__checkTokenResponse_->soap_get(soap, "ns1:checkTokenResponse", "ns1:checkTokenResponse");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__registerThisUnit(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__registerThisUnit *ns1__registerThisUnit_, ns1__registerThisUnitResponse *ns1__registerThisUnitResponse_)
{	struct __ns1__registerThisUnit soap_tmp___ns1__registerThisUnit;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080/gingko/gkws/GingkoDigitalService http://localhost:8080/gingko/gkws/GingkoLoginService http://localhost:8080/gingko/gkws/GingkoUnitService http://localhost:8080/gingko/gkws/GingkoUserService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__registerThisUnit.ns1__registerThisUnit_ = ns1__registerThisUnit_;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__registerThisUnit(soap, &soap_tmp___ns1__registerThisUnit);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__registerThisUnit(soap, &soap_tmp___ns1__registerThisUnit, "-ns1:registerThisUnit", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__registerThisUnit(soap, &soap_tmp___ns1__registerThisUnit, "-ns1:registerThisUnit", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__registerThisUnitResponse_)
		return soap_closesock(soap);
	ns1__registerThisUnitResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__registerThisUnitResponse_->soap_get(soap, "ns1:registerThisUnitResponse", "ns1:registerThisUnitResponse");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__findGingkoUnitInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__findGingkoUnitInfo *ns1__findGingkoUnitInfo_, ns1__findGingkoUnitInfoResponse *ns1__findGingkoUnitInfoResponse_)
{	struct __ns1__findGingkoUnitInfo soap_tmp___ns1__findGingkoUnitInfo;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080/gingko/gkws/GingkoDigitalService http://localhost:8080/gingko/gkws/GingkoLoginService http://localhost:8080/gingko/gkws/GingkoUnitService http://localhost:8080/gingko/gkws/GingkoUserService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__findGingkoUnitInfo.ns1__findGingkoUnitInfo_ = ns1__findGingkoUnitInfo_;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__findGingkoUnitInfo(soap, &soap_tmp___ns1__findGingkoUnitInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__findGingkoUnitInfo(soap, &soap_tmp___ns1__findGingkoUnitInfo, "-ns1:findGingkoUnitInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__findGingkoUnitInfo(soap, &soap_tmp___ns1__findGingkoUnitInfo, "-ns1:findGingkoUnitInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__findGingkoUnitInfoResponse_)
		return soap_closesock(soap);
	ns1__findGingkoUnitInfoResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__findGingkoUnitInfoResponse_->soap_get(soap, "ns1:findGingkoUnitInfoResponse", "ns1:findGingkoUnitInfoResponse");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__bindingGingkoUser(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__bindingGingkoUser *ns1__bindingGingkoUser_, ns1__bindingGingkoUserResponse *ns1__bindingGingkoUserResponse_)
{	struct __ns1__bindingGingkoUser soap_tmp___ns1__bindingGingkoUser;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080/gingko/gkws/GingkoDigitalService http://localhost:8080/gingko/gkws/GingkoLoginService http://localhost:8080/gingko/gkws/GingkoUnitService http://localhost:8080/gingko/gkws/GingkoUserService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__bindingGingkoUser.ns1__bindingGingkoUser_ = ns1__bindingGingkoUser_;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__bindingGingkoUser(soap, &soap_tmp___ns1__bindingGingkoUser);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__bindingGingkoUser(soap, &soap_tmp___ns1__bindingGingkoUser, "-ns1:bindingGingkoUser", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__bindingGingkoUser(soap, &soap_tmp___ns1__bindingGingkoUser, "-ns1:bindingGingkoUser", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__bindingGingkoUserResponse_)
		return soap_closesock(soap);
	ns1__bindingGingkoUserResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__bindingGingkoUserResponse_->soap_get(soap, "ns1:bindingGingkoUserResponse", "ns1:bindingGingkoUserResponse");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__findUserByLoginId(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__findUserByLoginId *ns1__findUserByLoginId_, ns1__findUserByLoginIdResponse *ns1__findUserByLoginIdResponse_)
{	struct __ns1__findUserByLoginId soap_tmp___ns1__findUserByLoginId;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080/gingko/gkws/GingkoDigitalService http://localhost:8080/gingko/gkws/GingkoLoginService http://localhost:8080/gingko/gkws/GingkoUnitService http://localhost:8080/gingko/gkws/GingkoUserService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__findUserByLoginId.ns1__findUserByLoginId_ = ns1__findUserByLoginId_;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__findUserByLoginId(soap, &soap_tmp___ns1__findUserByLoginId);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__findUserByLoginId(soap, &soap_tmp___ns1__findUserByLoginId, "-ns1:findUserByLoginId", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__findUserByLoginId(soap, &soap_tmp___ns1__findUserByLoginId, "-ns1:findUserByLoginId", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__findUserByLoginIdResponse_)
		return soap_closesock(soap);
	ns1__findUserByLoginIdResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__findUserByLoginIdResponse_->soap_get(soap, "ns1:findUserByLoginIdResponse", "ns1:findUserByLoginIdResponse");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__searchUsers(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__searchUsers *ns1__searchUsers_, ns1__searchUsersResponse *ns1__searchUsersResponse_)
{	struct __ns1__searchUsers soap_tmp___ns1__searchUsers;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080/gingko/gkws/GingkoDigitalService http://localhost:8080/gingko/gkws/GingkoLoginService http://localhost:8080/gingko/gkws/GingkoUnitService http://localhost:8080/gingko/gkws/GingkoUserService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__searchUsers.ns1__searchUsers_ = ns1__searchUsers_;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__searchUsers(soap, &soap_tmp___ns1__searchUsers);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__searchUsers(soap, &soap_tmp___ns1__searchUsers, "-ns1:searchUsers", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__searchUsers(soap, &soap_tmp___ns1__searchUsers, "-ns1:searchUsers", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__searchUsersResponse_)
		return soap_closesock(soap);
	ns1__searchUsersResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__searchUsersResponse_->soap_get(soap, "ns1:searchUsersResponse", "ns1:searchUsersResponse");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__findUserByGingkoId(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__findUserByGingkoId *ns1__findUserByGingkoId_, ns1__findUserByGingkoIdResponse *ns1__findUserByGingkoIdResponse_)
{	struct __ns1__findUserByGingkoId soap_tmp___ns1__findUserByGingkoId;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080/gingko/gkws/GingkoDigitalService http://localhost:8080/gingko/gkws/GingkoLoginService http://localhost:8080/gingko/gkws/GingkoUnitService http://localhost:8080/gingko/gkws/GingkoUserService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__findUserByGingkoId.ns1__findUserByGingkoId_ = ns1__findUserByGingkoId_;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__findUserByGingkoId(soap, &soap_tmp___ns1__findUserByGingkoId);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__findUserByGingkoId(soap, &soap_tmp___ns1__findUserByGingkoId, "-ns1:findUserByGingkoId", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__findUserByGingkoId(soap, &soap_tmp___ns1__findUserByGingkoId, "-ns1:findUserByGingkoId", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__findUserByGingkoIdResponse_)
		return soap_closesock(soap);
	ns1__findUserByGingkoIdResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__findUserByGingkoIdResponse_->soap_get(soap, "ns1:findUserByGingkoIdResponse", "ns1:findUserByGingkoIdResponse");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__changePassword(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__changePassword *ns1__changePassword_, ns1__changePasswordResponse *ns1__changePasswordResponse_)
{	struct __ns1__changePassword soap_tmp___ns1__changePassword;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080/gingko/gkws/GingkoDigitalService http://localhost:8080/gingko/gkws/GingkoLoginService http://localhost:8080/gingko/gkws/GingkoUnitService http://localhost:8080/gingko/gkws/GingkoUserService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__changePassword.ns1__changePassword_ = ns1__changePassword_;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__changePassword(soap, &soap_tmp___ns1__changePassword);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__changePassword(soap, &soap_tmp___ns1__changePassword, "-ns1:changePassword", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__changePassword(soap, &soap_tmp___ns1__changePassword, "-ns1:changePassword", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__changePasswordResponse_)
		return soap_closesock(soap);
	ns1__changePasswordResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__changePasswordResponse_->soap_get(soap, "ns1:changePasswordResponse", "ns1:changePasswordResponse");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__requestPermission(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__requestPermission *ns1__requestPermission_, ns1__requestPermissionResponse *ns1__requestPermissionResponse_)
{	struct __ns1__requestPermission soap_tmp___ns1__requestPermission;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080/gingko/gkws/GingkoDigitalService http://localhost:8080/gingko/gkws/GingkoLoginService http://localhost:8080/gingko/gkws/GingkoUnitService http://localhost:8080/gingko/gkws/GingkoUserService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__requestPermission.ns1__requestPermission_ = ns1__requestPermission_;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__requestPermission(soap, &soap_tmp___ns1__requestPermission);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__requestPermission(soap, &soap_tmp___ns1__requestPermission, "-ns1:requestPermission", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__requestPermission(soap, &soap_tmp___ns1__requestPermission, "-ns1:requestPermission", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__requestPermissionResponse_)
		return soap_closesock(soap);
	ns1__requestPermissionResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__requestPermissionResponse_->soap_get(soap, "ns1:requestPermissionResponse", "ns1:requestPermissionResponse");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__deleteDigitalInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__deleteDigitalInfo *ns1__deleteDigitalInfo_, ns1__deleteDigitalInfoResponse *ns1__deleteDigitalInfoResponse_)
{	struct __ns1__deleteDigitalInfo soap_tmp___ns1__deleteDigitalInfo;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080/gingko/gkws/GingkoDigitalService http://localhost:8080/gingko/gkws/GingkoLoginService http://localhost:8080/gingko/gkws/GingkoUnitService http://localhost:8080/gingko/gkws/GingkoUserService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__deleteDigitalInfo.ns1__deleteDigitalInfo_ = ns1__deleteDigitalInfo_;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__deleteDigitalInfo(soap, &soap_tmp___ns1__deleteDigitalInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__deleteDigitalInfo(soap, &soap_tmp___ns1__deleteDigitalInfo, "-ns1:deleteDigitalInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__deleteDigitalInfo(soap, &soap_tmp___ns1__deleteDigitalInfo, "-ns1:deleteDigitalInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__deleteDigitalInfoResponse_)
		return soap_closesock(soap);
	ns1__deleteDigitalInfoResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__deleteDigitalInfoResponse_->soap_get(soap, "ns1:deleteDigitalInfoResponse", "ns1:deleteDigitalInfoResponse");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__findDigitalInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__findDigitalInfo *ns1__findDigitalInfo_, ns1__findDigitalInfoResponse *ns1__findDigitalInfoResponse_)
{	struct __ns1__findDigitalInfo soap_tmp___ns1__findDigitalInfo;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080/gingko/gkws/GingkoDigitalService http://localhost:8080/gingko/gkws/GingkoLoginService http://localhost:8080/gingko/gkws/GingkoUnitService http://localhost:8080/gingko/gkws/GingkoUserService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__findDigitalInfo.ns1__findDigitalInfo_ = ns1__findDigitalInfo_;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__findDigitalInfo(soap, &soap_tmp___ns1__findDigitalInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__findDigitalInfo(soap, &soap_tmp___ns1__findDigitalInfo, "-ns1:findDigitalInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__findDigitalInfo(soap, &soap_tmp___ns1__findDigitalInfo, "-ns1:findDigitalInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__findDigitalInfoResponse_)
		return soap_closesock(soap);
	ns1__findDigitalInfoResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__findDigitalInfoResponse_->soap_get(soap, "ns1:findDigitalInfoResponse", "ns1:findDigitalInfoResponse");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__findAssignedPermission(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__findAssignedPermission *ns1__findAssignedPermission_, ns1__findAssignedPermissionResponse *ns1__findAssignedPermissionResponse_)
{	struct __ns1__findAssignedPermission soap_tmp___ns1__findAssignedPermission;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080/gingko/gkws/GingkoDigitalService http://localhost:8080/gingko/gkws/GingkoLoginService http://localhost:8080/gingko/gkws/GingkoUnitService http://localhost:8080/gingko/gkws/GingkoUserService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__findAssignedPermission.ns1__findAssignedPermission_ = ns1__findAssignedPermission_;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__findAssignedPermission(soap, &soap_tmp___ns1__findAssignedPermission);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__findAssignedPermission(soap, &soap_tmp___ns1__findAssignedPermission, "-ns1:findAssignedPermission", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__findAssignedPermission(soap, &soap_tmp___ns1__findAssignedPermission, "-ns1:findAssignedPermission", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__findAssignedPermissionResponse_)
		return soap_closesock(soap);
	ns1__findAssignedPermissionResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__findAssignedPermissionResponse_->soap_get(soap, "ns1:findAssignedPermissionResponse", "ns1:findAssignedPermissionResponse");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__assignPermission(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__assignPermission *ns1__assignPermission_, ns1__assignPermissionResponse *ns1__assignPermissionResponse_)
{	struct __ns1__assignPermission soap_tmp___ns1__assignPermission;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080/gingko/gkws/GingkoDigitalService http://localhost:8080/gingko/gkws/GingkoLoginService http://localhost:8080/gingko/gkws/GingkoUnitService http://localhost:8080/gingko/gkws/GingkoUserService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__assignPermission.ns1__assignPermission_ = ns1__assignPermission_;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__assignPermission(soap, &soap_tmp___ns1__assignPermission);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__assignPermission(soap, &soap_tmp___ns1__assignPermission, "-ns1:assignPermission", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__assignPermission(soap, &soap_tmp___ns1__assignPermission, "-ns1:assignPermission", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__assignPermissionResponse_)
		return soap_closesock(soap);
	ns1__assignPermissionResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__assignPermissionResponse_->soap_get(soap, "ns1:assignPermissionResponse", "ns1:assignPermissionResponse");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__findDigitalPermission(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__findDigitalPermission *ns1__findDigitalPermission_, ns1__findDigitalPermissionResponse *ns1__findDigitalPermissionResponse_)
{	struct __ns1__findDigitalPermission soap_tmp___ns1__findDigitalPermission;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080/gingko/gkws/GingkoDigitalService http://localhost:8080/gingko/gkws/GingkoLoginService http://localhost:8080/gingko/gkws/GingkoUnitService http://localhost:8080/gingko/gkws/GingkoUserService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__findDigitalPermission.ns1__findDigitalPermission_ = ns1__findDigitalPermission_;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__findDigitalPermission(soap, &soap_tmp___ns1__findDigitalPermission);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__findDigitalPermission(soap, &soap_tmp___ns1__findDigitalPermission, "-ns1:findDigitalPermission", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__findDigitalPermission(soap, &soap_tmp___ns1__findDigitalPermission, "-ns1:findDigitalPermission", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__findDigitalPermissionResponse_)
		return soap_closesock(soap);
	ns1__findDigitalPermissionResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__findDigitalPermissionResponse_->soap_get(soap, "ns1:findDigitalPermissionResponse", "ns1:findDigitalPermissionResponse");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__updateDigitalInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__updateDigitalInfo *ns1__updateDigitalInfo_, ns1__updateDigitalInfoResponse *ns1__updateDigitalInfoResponse_)
{	struct __ns1__updateDigitalInfo soap_tmp___ns1__updateDigitalInfo;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080/gingko/gkws/GingkoDigitalService http://localhost:8080/gingko/gkws/GingkoLoginService http://localhost:8080/gingko/gkws/GingkoUnitService http://localhost:8080/gingko/gkws/GingkoUserService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__updateDigitalInfo.ns1__updateDigitalInfo_ = ns1__updateDigitalInfo_;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__updateDigitalInfo(soap, &soap_tmp___ns1__updateDigitalInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__updateDigitalInfo(soap, &soap_tmp___ns1__updateDigitalInfo, "-ns1:updateDigitalInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__updateDigitalInfo(soap, &soap_tmp___ns1__updateDigitalInfo, "-ns1:updateDigitalInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__updateDigitalInfoResponse_)
		return soap_closesock(soap);
	ns1__updateDigitalInfoResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__updateDigitalInfoResponse_->soap_get(soap, "ns1:updateDigitalInfoResponse", "ns1:updateDigitalInfoResponse");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__createDigitalInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__createDigitalInfo *ns1__createDigitalInfo_, ns1__createDigitalInfoResponse *ns1__createDigitalInfoResponse_)
{	struct __ns1__createDigitalInfo soap_tmp___ns1__createDigitalInfo;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080/gingko/gkws/GingkoDigitalService http://localhost:8080/gingko/gkws/GingkoLoginService http://localhost:8080/gingko/gkws/GingkoUnitService http://localhost:8080/gingko/gkws/GingkoUserService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__createDigitalInfo.ns1__createDigitalInfo_ = ns1__createDigitalInfo_;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__createDigitalInfo(soap, &soap_tmp___ns1__createDigitalInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__createDigitalInfo(soap, &soap_tmp___ns1__createDigitalInfo, "-ns1:createDigitalInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__createDigitalInfo(soap, &soap_tmp___ns1__createDigitalInfo, "-ns1:createDigitalInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__createDigitalInfoResponse_)
		return soap_closesock(soap);
	ns1__createDigitalInfoResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__createDigitalInfoResponse_->soap_get(soap, "ns1:createDigitalInfoResponse", "ns1:createDigitalInfoResponse");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.cpp */
